# Generated by Django 4.0.6 on 2022-08-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urunler2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(blank=True, null=True, upload_to='urunresmimleri/', verbose_name='Ürün Resmi')),
                ('price', models.DecimalField(decimal_places=100, max_digits=500000)),
                ('about', models.TextField(max_length=500, verbose_name='Ürün Hakkında')),
            ],
        ),
        migrations.AlterField(
            model_name='urunler',
            name='ucret',
            field=models.DecimalField(decimal_places=100, max_digits=500000),
        ),
    ]
