# Generated by Django 4.0.6 on 2022-08-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favories', '0002_urunler2_alter_urunler_ucret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urunler',
            name='ucret',
            field=models.DecimalField(decimal_places=1, max_digits=1),
        ),
        migrations.AlterField(
            model_name='urunler2',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=1),
        ),
    ]
