# Generated by Django 4.0.6 on 2022-08-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favories', '0004_delete_urunler2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urunler',
            name='ucret',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
