# Generated by Django 4.0.6 on 2022-08-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favories', '0005_alter_urunler_ucret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urunler',
            name='ucret',
            field=models.IntegerField(default=0, verbose_name='Ücret'),
        ),
    ]
