# Generated by Django 4.0.6 on 2022-08-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favories', '0006_alter_urunler_ucret'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urunler2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gorsel2', models.FileField(blank=True, null=True, upload_to='resim/', verbose_name='Ürün Resmi')),
                ('ucret2', models.IntegerField(default=0, verbose_name='Ücret')),
                ('hakkinda2', models.TextField(max_length=400, verbose_name='Açıklama')),
            ],
        ),
    ]
