# Generated by Django 4.0.6 on 2022-09-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favories', '0008_delete_urunler2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urunler',
            name='gorsel',
            field=models.ImageField(blank=True, null=True, upload_to='resim/', verbose_name='Ürün Resmi'),
        ),
    ]
