# Generated by Django 4.0.6 on 2022-08-01 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_regisyerform_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegisyerForm',
            new_name='RegisterForm',
        ),
    ]
