# Generated by Django 4.0.6 on 2022-08-04 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_regisyerform_registerform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisterForm',
        ),
    ]
