# Generated by Django 4.0.6 on 2022-08-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_delete_registerform'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='İsim-Soyisim')),
                ('email', models.TextField(max_length=30, verbose_name='E-mail')),
                ('password', models.IntegerField(verbose_name='Şifre')),
            ],
        ),
    ]
