# Generated by Django 4.0.6 on 2022-08-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerform',
            name='email',
            field=models.EmailField(max_length=30, verbose_name='E-mail'),
        ),
    ]
