# Generated by Django 4.0.6 on 2022-08-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_registerform_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerform',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='registerform',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
