# Generated by Django 4.0.6 on 2022-08-05 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0009_alter_registerform_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerform',
            name='password',
        ),
        migrations.AddField(
            model_name='registerform',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
