# Generated by Django 4.0.6 on 2022-08-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_registerform_password_registerform_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerform',
            name='owner',
        ),
        migrations.AddField(
            model_name='registerform',
            name='password',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
