# Generated by Django 4.0.6 on 2022-08-05 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_delete_loginform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerform',
            old_name='password',
            new_name='password1',
        ),
    ]
