# Generated by Django 4.0.6 on 2022-08-06 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_loginform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginform',
            old_name='email',
            new_name='emaill',
        ),
    ]
