# Generated by Django 4.0.6 on 2022-08-06 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_rename_email_loginform_emaill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginForm',
        ),
        migrations.DeleteModel(
            name='RegisterForm',
        ),
    ]
