# Generated by Django 4.0.6 on 2022-08-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_urunler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urunler',
            name='gorsel',
            field=models.FileField(blank=True, null=True, upload_to='resim/', verbose_name='Ürün Resmi'),
        ),
    ]
