# Generated by Django 4.0.6 on 2022-08-01 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_urunler_gorsel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Urunler',
        ),
    ]
