# Generated by Django 4.0.6 on 2022-08-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_delete_urunler'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urunler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gorsel', models.FileField(blank=True, null=True, upload_to='resim/', verbose_name='Ürün Resmi')),
                ('ucret', models.IntegerField(default=0)),
                ('hakkinda', models.TextField(max_length=400, verbose_name='Açıklama')),
            ],
        ),
    ]
