# Generated by Django 4.0.6 on 2022-08-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_delete_urunler'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name='Kullanıcı adını yazınız')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail yazınız')),
                ('subject', models.TextField(max_length=500, verbose_name='Mesajınızı yazınız')),
            ],
        ),
    ]
