# Generated by Django 4.0.6 on 2022-08-06 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_contact_message_alter_contact_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
