# Generated by Django 4.0.6 on 2022-08-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_contact_name_alter_contact_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urunform',
            name='fiyat',
            field=models.DecimalField(decimal_places=100, max_digits=500000),
        ),
    ]
