# Generated by Django 4.0.6 on 2022-08-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_urunform2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urunform',
            name='fiyat',
            field=models.DecimalField(decimal_places=1, max_digits=1),
        ),
        migrations.AlterField(
            model_name='urunform2',
            name='fee',
            field=models.DecimalField(decimal_places=1, max_digits=1),
        ),
    ]
