# Generated by Django 4.0.6 on 2022-08-08 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_urunform_fiyat_alter_urunform2_fee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UrunForm2',
        ),
    ]
