# Generated by Django 4.0.6 on 2022-08-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_delete_urunform2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urunform',
            name='fiyat',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
