# Generated by Django 4.0.6 on 2022-08-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_urunform_fiyat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urunform',
            name='fiyat',
            field=models.IntegerField(default=0),
        ),
    ]
