# Generated by Django 4.0.6 on 2022-08-08 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_product_urunform_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urunform',
            name='category',
            field=models.ManyToManyField(to='products.category'),
        ),
        migrations.RemoveField(
            model_name='urunform',
            name='product',
        ),
        migrations.AddField(
            model_name='urunform',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
