# Generated by Django 4.0.6 on 2022-08-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_urunform_category_remove_urunform_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urunform',
            name='aciklama',
            field=models.CharField(max_length=400, verbose_name='Açıklama'),
        ),
    ]
