# Generated by Django 4.0.6 on 2022-08-09 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_category2_product2_urunform2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urunform2',
            name='category2',
        ),
        migrations.RemoveField(
            model_name='urunform2',
            name='product2',
        ),
        migrations.DeleteModel(
            name='Category2',
        ),
        migrations.DeleteModel(
            name='product2',
        ),
        migrations.DeleteModel(
            name='UrunForm2',
        ),
    ]
