# Generated by Django 4.0.6 on 2022-09-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_contact_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urunform',
            name='resim',
            field=models.ImageField(blank=True, null=True, upload_to='urunresmi/', verbose_name='Ürün Resmi'),
        ),
    ]
