# Generated by Django 4.0.6 on 2022-09-01 19:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_alter_urunform_resim'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
